name: MusicBox
main: MusicBox\MusicBox
api: 3.0.0
version: 1.0
author: FreakingDev
description: Play music in your server


commands:
 music:
  permission: MusicBox.music
  description: Manage the music in your server
  usage: /music <start|stop|next>

permissions:
 MusicBox:
  default: op
  description: MusicBox Commands
  children:
     MusicBox.music:
      default: op
      description: MusicBox Commands
    
